# Non-Inferiority of Max Aggregation

## Fetch Data

In [41]:
import mlflow
import pandas as pd

def fetch_table(uri: str) -> str:
    return mlflow.artifacts.download_artifacts(uri)

model_preds = {}

# pgp
model_preds["pgp"] = {}

pgp_max = pd.read_json(
    fetch_table("mlflow-artifacts:/65/107c573695df44148f58f87f5ebc663b/artifacts/tables/aggregated_predictions_corrected.json"),
    orient="split"
)
pgp_mpm = pd.read_json(
    fetch_table("mlflow-artifacts:/65/6e495b406c6445aeb121493efa3e5bb5/artifacts/tables/aggregated_predictions_corrected.json"),
    orient="split"
)
pgp_topk = pd.read_json(
    fetch_table("mlflow-artifacts:/65/8e99ad132b574e09a7fc5d27002adc68/artifacts/tables/aggregated_predictions_corrected.json"),
    orient="split"
)
pgp_span = pd.read_json(
    fetch_table("mlflow-artifacts:/65/ec752a886d134fc19aaeb66f4476fa63/artifacts/tables/aggregated_predictions_corrected.json"),
    orient="split"
)

model_preds["pgp"]["max"] = pgp_max["prediction"]
model_preds["pgp"]["mpm"] = pgp_mpm["pred_1"]
model_preds["pgp"]["topk"] = pgp_topk["pred_kernel_size=1_k=4"]
model_preds["pgp"]["span"] = pgp_span["pred_k=4"]

# virchow2
model_preds["virchow2"] = {}
virchow2_max = pd.read_json(
    fetch_table("mlflow-artifacts:/65/55c83a014afa4d65979b0c549cbe5397/artifacts/tables/aggregated_predictions_corrected.json"),
    orient="split"
)
virchow2_mpm = pd.read_json(
    fetch_table("mlflow-artifacts:/65/d3b4d174850247febd1581d2bbc64bcd/artifacts/tables/aggregated_predictions_corrected.json"),
    orient="split"
)
virchow2_topk = pd.read_json(
    fetch_table("mlflow-artifacts:/65/3e3c944a7cb449d8b9c70a83a93a64c7/artifacts/tables/aggregated_predictions_corrected.json"),
    orient="split"
)
virchow2_span = pd.read_json(
    fetch_table("mlflow-artifacts:/65/71ead3aa65b849a082d178d627b74bcb/artifacts/tables/aggregated_predictions_corrected.json"),
    orient="split"
)

model_preds["virchow2"]["max"] = virchow2_max["prediction"]
model_preds["virchow2"]["mpm"] = virchow2_mpm["pred_2"]
model_preds["virchow2"]["topk"] = virchow2_topk["pred_kernel_size=2_k=3"]
model_preds["virchow2"]["span"] = virchow2_span["pred_k=5"]

# resnet50
model_preds["resnet50"] = {}
resnet50_max = pd.read_json(
    fetch_table("mlflow-artifacts:/65/94561b6417ea4f888495fdcb799555e2/artifacts/tables/aggregated_predictions_corrected.json"),
    orient="split"
)
resnet50_mpm = pd.read_json(
    fetch_table("mlflow-artifacts:/65/46a594a334ef4bbe9fdc7ba73250b12a/artifacts/tables/aggregated_predictions_corrected.json"),
    orient="split"
)
resnet50_topk = pd.read_json(
    fetch_table("mlflow-artifacts:/65/bcf0312c738c460381bde996e5cb93d8/artifacts/tables/aggregated_predictions_corrected.json"),
    orient="split"
)
resnet50_span = pd.read_json(
    fetch_table("mlflow-artifacts:/65/ccd4a8001874439f8c860eefa5d41fbe/artifacts/tables/aggregated_predictions_corrected.json"),
    orient="split"
)

model_preds["resnet50"]["max"] = resnet50_max["prediction"]
model_preds["resnet50"]["mpm"] = resnet50_mpm["pred_5"]
model_preds["resnet50"]["topk"] = resnet50_topk["pred_kernel_size=4_k=4"]
model_preds["resnet50"]["span"] = resnet50_span["pred_k=4"]

# resnet50-stain
model_preds["resnet50_stain"] = {}
resnet50_stain_max = pd.read_json(
    fetch_table("mlflow-artifacts:/65/b982f0b741b442a5b7c7f16cae8fb155/artifacts/tables/aggregated_predictions_corrected.json"),
    orient="split"
)
resnet50_stain_mpm = pd.read_json(
    fetch_table("mlflow-artifacts:/65/bdbd2d8aa5fa44a581281f2396afa4a7/artifacts/tables/aggregated_predictions_corrected.json"),
    orient="split"
)
resnet50_stain_topk = pd.read_json(
    fetch_table("mlflow-artifacts:/65/51be8706f3fb401ab455ecf2c7b64b93/artifacts/tables/aggregated_predictions_corrected.json"),
    orient="split"
)
resnet50_stain_span = pd.read_json(
    fetch_table("mlflow-artifacts:/65/647659f90b8144989062a73882e50d1f/artifacts/tables/aggregated_predictions_corrected.json"),
    orient="split"
)

model_preds["resnet50_stain"]["max"] = resnet50_stain_max["prediction"]
model_preds["resnet50_stain"]["mpm"] = resnet50_stain_mpm["pred_3"]
model_preds["resnet50_stain"]["topk"] = resnet50_stain_topk["pred_kernel_size=1_k=4"]
model_preds["resnet50_stain"]["span"] = resnet50_stain_span["pred_k=4"]

# vgg16
model_preds["vgg16"] = {}
vgg16_max = pd.read_json(
    fetch_table("mlflow-artifacts:/65/4c57d5df00fb4b26baa7ae761f4824c8/artifacts/tables/aggregated_predictions_corrected.json"),
    orient="split"
)
vgg16_mpm = pd.read_json(
    fetch_table("mlflow-artifacts:/65/1a1eeddaf5864f6aa8b0d9e8a7f887ec/artifacts/tables/aggregated_predictions_corrected.json"),
    orient="split"
)
vgg16_topk = pd.read_json(
    fetch_table("mlflow-artifacts:/65/3e2d76776e2e4ce5ac25041d7b97fd7d/artifacts/tables/aggregated_predictions_corrected.json"),
    orient="split"
)
vgg16_span = pd.read_json(
    fetch_table("mlflow-artifacts:/65/1981e514a7be46d7a1188bd93c34eefe/artifacts/tables/aggregated_predictions_corrected.json"),
    orient="split"
)

model_preds["vgg16"]["max"] = vgg16_max["prediction"]
model_preds["vgg16"]["mpm"] = vgg16_mpm["pred_1"]
model_preds["vgg16"]["topk"] = vgg16_topk["pred_kernel_size=1_k=4"]
model_preds["vgg16"]["span"] = vgg16_span["pred_k=3"]


# vgg16-stain
model_preds["vgg16_stain"] = {}

vgg16_stain_max = pd.read_json(
    fetch_table("mlflow-artifacts:/65/1c08494a5de648d4b7f025aa89ac1be9/artifacts/tables/aggregated_predictions_corrected.json"),
    orient="split"
)
vgg16_stain_mpm = pd.read_json(
    fetch_table("mlflow-artifacts:/65/de09807020fa4d4ca15b840692fedf82/artifacts/tables/aggregated_predictions_corrected.json"),
    orient="split"
)
vgg16_stain_topk = pd.read_json(
    fetch_table("mlflow-artifacts:/65/d63f6775ddf44a4c93a934298fe10d22/artifacts/tables/aggregated_predictions_corrected.json"),
    orient="split"
)
vgg16_stain_span = pd.read_json(
    fetch_table("mlflow-artifacts:/65/8d45a014dece415bababfabda2981a3f/artifacts/tables/aggregated_predictions_corrected.json"),
    orient="split"
)

model_preds["vgg16_stain"]["max"] = vgg16_stain_max["prediction"]
model_preds["vgg16_stain"]["mpm"] = vgg16_stain_mpm["pred_1"]
model_preds["vgg16_stain"]["topk"] = vgg16_stain_topk["pred_kernel_size=1_k=2"]
model_preds["vgg16_stain"]["span"] = vgg16_stain_span["pred_k=3"]


# gvit
model_preds["gvit"] = {}
gvit_max = pd.read_json(
    fetch_table("mlflow-artifacts:/65/14059f41cc864b84b0c45a8967150b4a/artifacts/tables/aggregated_predictions.json"),
    orient="split"
)
gvit_mpm = pd.read_json(
    fetch_table("mlflow-artifacts:/65/872981529bf54121822bab214866c376/artifacts/tables/aggregated_predictions.json"),
    orient="split"
)
gvit_topk = pd.read_json(
    fetch_table("mlflow-artifacts:/65/15eb8d742c1f439a8ede9af78c328fb0/artifacts/tables/aggregated_predictions.json"),
    orient="split"
)
gvit_span = pd.read_json(
    fetch_table("mlflow-artifacts:/65/86c76dfadc5d4592a6f8e7521ff18ae5/artifacts/tables/aggregated_predictions.json"),
    orient="split"
)


model_preds["gvit"]["max"] = gvit_max["prediction"]
model_preds["gvit"]["mpm"] = gvit_mpm["pred_kernel_size=1"]
model_preds["gvit"]["topk"] = gvit_topk["pred_kernel_size=1_k=2"]
model_preds["gvit"]["span"] = gvit_span["pred_k=5"]

# gvit-stain
model_preds["gvit_stain"] = {}
gvit_stain_max = pd.read_json(
    fetch_table("mlflow-artifacts:/65/2f9507b977224978a0b16d30ffa7416e/artifacts/tables/aggregated_predictions.json"),
    orient="split"
)
gvit_stain_mpm = pd.read_json(
    fetch_table("mlflow-artifacts:/65/0a0ac745e45d49648c68ba667732b67a/artifacts/tables/aggregated_predictions.json"),
    orient="split"
)
gvit_stain_topk = pd.read_json(
    fetch_table("mlflow-artifacts:/65/53f5ad7868e94fe7b3a09ec1175c9f7b/artifacts/tables/aggregated_predictions.json"),
    orient="split"
)
gvit_stain_span = pd.read_json(
    fetch_table("mlflow-artifacts:/65/6461ccf2b2a646048f808bdef6a6246b/artifacts/tables/aggregated_predictions.json"),
    orient="split"
)

model_preds["gvit_stain"]["max"] = gvit_stain_max["prediction"]
model_preds["gvit_stain"]["mpm"] = gvit_stain_mpm["pred_kernel_size=6"]
model_preds["gvit_stain"]["topk"] = gvit_stain_topk["pred_kernel_size=2_k=4"]
model_preds["gvit_stain"]["span"] = gvit_stain_span["pred_k=5"]

gt = gvit_stain_max["target"] # everywhere same

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 114.49it/s]
Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 115.98it/s]
Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 125.97it/s]
Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 126.63it/s]
Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 120.48it/s]
Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 137.12it/s]
Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 122.47it/s]
Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 133.40it/s]
Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 137.21it/s]
Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 153.13it/s]
Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 119.43it/s]
Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 151.15it/s]
Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 126.37it/s]
Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 132.22it/s]
Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 125.56it/s]
Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 131.73it/s]
Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 126.79it/s]
Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 129.87it/s]
Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 120.35it/s]
Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 141.28it/s]
Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 152.06it/s]
Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 147.50it/s]
Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 143.05it/s]
Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 132.05it/s]
Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 141.87it/s]
Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 137.37it/s]
Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 131.46it/s]
Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 137.77it/s]
Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 125.94it/s]
Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 138.02it/s]
Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 128.20it/s]
Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 134.05it/s]

## Sanity Check

In [42]:
assert len(model_preds) == 8 # 8 models

for model, preds in model_preds.items():
    assert len(preds) == 4 # 4 aggr. methods

    for pred_type, aggr_scores in preds.items():
        assert pred_type in ["max", "mpm", "topk", "span"]
        assert len(aggr_scores) == 424

assert len(gt) == 424

## Per-Model Non-Inferiority

In [43]:
import numpy as np
from numpy.typing import NDArray
from sklearn.metrics import roc_auc_score

def bootstrap_auc_diff(
    y: NDArray[np.int_],
    scores_max: NDArray[np.floating],
    scores_other: NDArray[np.floating],
    n_boot: int = 10_000,
    seed: int = 0
) -> NDArray[np.floating]:
    """
    Bootstrap distribution of AUC differences:

        Δ = AUC(other) - AUC(max)

    Parameters
    ----------
    y : array-like of shape (n_samples,)
        Binary ground-truth labels (0/1).
    scores_max : array-like of shape (n_samples,)
        Prediction scores from max aggregation.
    scores_other : array-like of shape (n_samples,)
        Prediction scores from another aggregation method.
    n_boot : int
        Number of bootstrap resamples.
    seed : int
        Random seed for reproducibility.

    Returns
    -------
    NDArray[np.float_]
        Bootstrap samples of ΔAUC.
    """
    """
    Returns bootstrap distribution of:
        Δ = AUC(other) - AUC(max)
    """
    rng = np.random.default_rng(seed)
    n = len(y)

    deltas = []

    for _ in range(n_boot):
        idx = rng.integers(0, n, n)

        y_b = y[idx]

        # skip degenerate samples
        if len(np.unique(y_b)) < 2:
            continue

        auc_max = roc_auc_score(y_b, scores_max[idx])
        auc_other = roc_auc_score(y_b, scores_other[idx])

        deltas.append(auc_other - auc_max)

    return np.array(deltas)

In [44]:
from typing import Any

def non_inferiority_summary(
    deltas: np.ndarray,
    delta: float,
) -> dict[str, Any]:
    """
    Convert bootstrap Δ distribution into NI decision
    """

    mean_delta = float(np.mean(deltas))
    lower = float(np.percentile(deltas, 2.5))
    upper = float(np.percentile(deltas, 97.5))
    upper_95 = float(np.percentile(deltas, 95))

    return {
        "mean_delta": mean_delta,
        "ci_95_lower": lower,
        "ci_95_upper": upper,
        "upper_95": upper_95,
        "non_inferior": upper_95 < delta
    }


def evaluate_single_model(
    model_name: str,
    y: np.ndarray,
    delta: float = 0.01,
    n_boot: int = 10_000
) -> pd.DataFrame:
    """
    Compare max vs all aggregation methods for one model
    """

    results = []

    preds = model_preds[model_name]
    max_scores = np.asarray(preds["max"])

    for method in ["mpm", "topk", "span"]:

        other_scores = np.asarray(preds[method])

        deltas = bootstrap_auc_diff(
            y=y,
            scores_max=max_scores,
            scores_other=other_scores,
            n_boot=n_boot,
            seed=42
        )

        stats = non_inferiority_summary(deltas, delta=delta)

        stats.update({
            "model": model_name,
            "method": method
        })

        results.append(stats)

    return pd.DataFrame(results)

In [45]:
margin = 0.02 # We consider max acceptable if it is not worse by more than 0.02 AUC

pgp_df = evaluate_single_model("pgp", gt, margin)
virchow2_df = evaluate_single_model("virchow2", gt, margin)
resnet50_df = evaluate_single_model("resnet50", gt, margin)
resnet50_stain_df = evaluate_single_model("resnet50_stain", gt, margin)
vgg16_df = evaluate_single_model("vgg16", gt, margin)
vgg16_stain_df = evaluate_single_model("vgg16_stain", gt, margin)
gvit_df = evaluate_single_model("gvit", gt, margin)
gvit_stain_df = evaluate_single_model("gvit_stain", gt, margin)

In [46]:
pgp_df

   mean_delta  ci_95_lower  ci_95_upper  upper_95  non_inferior model method
0   -0.002863    -0.006358    -0.000254 -0.000581          True   pgp    mpm
1   -0.001487    -0.004108     0.000573  0.000278          True   pgp   topk
2   -0.046634    -0.067403    -0.028401 -0.031044          True   pgp   span

In [47]:
virchow2_df

,mean_delta,ci_95_lower,ci_95_upper,upper_95,non_inferior,model,method
0,0.001267,-0.001703,0.004353,0.003776,True,virchow2,mpm
1,0.002175,-0.000561,0.005194,0.004642,True,virchow2,topk
2,-0.060128,-0.083072,-0.039058,-0.042314,True,virchow2,span

In [53]:
resnet50_df

,mean_delta,ci_95_lower,ci_95_upper,upper_95,non_inferior,model,method
0,-0.002807,-0.016855,0.010913,0.008735,True,resnet50,mpm
1,0.000682,-0.012022,0.013038,0.011030,True,resnet50,topk
2,-0.008416,-0.042177,0.025310,0.019668,True,resnet50,span

In [48]:
resnet50_stain_df

,mean_delta,ci_95_lower,ci_95_upper,upper_95,non_inferior,model,method
0,0.005769,-0.007621,0.019181,0.017110,True,resnet50_stain,mpm
1,0.004001,-0.006204,0.014211,0.012437,True,resnet50_stain,topk
2,-0.008304,-0.041364,0.024890,0.019557,True,resnet50_stain,span

In [49]:
vgg16_df

   mean_delta  ci_95_lower  ci_95_upper  upper_95  non_inferior  model method
0   -0.003966    -0.016474     0.008049  0.006053          True  vgg16    mpm
1   -0.004667    -0.017835     0.007790  0.005831          True  vgg16   topk
2   -0.029711    -0.062006     0.002024 -0.002621          True  vgg16   span

In [50]:
vgg16_stain_df

,mean_delta,ci_95_lower,ci_95_upper,upper_95,non_inferior,model,method
0,-0.000396,-0.009486,0.008298,0.006960,True,vgg16_stain,mpm
1,0.000893,-0.007923,0.009326,0.008023,True,vgg16_stain,topk
2,-0.012769,-0.043978,0.018578,0.013766,True,vgg16_stain,span

In [51]:
gvit_df

   mean_delta  ci_95_lower  ci_95_upper  upper_95  non_inferior model method
0   -0.012938    -0.026815    -0.001941 -0.003372          True  gvit    mpm
1   -0.013193    -0.027134    -0.002308 -0.003820          True  gvit   topk
2   -0.403856    -0.428283    -0.377248 -0.382055          True  gvit   span

In [52]:
gvit_stain_df

,mean_delta,ci_95_lower,ci_95_upper,upper_95,non_inferior,model,method
0,-0.003424,-0.025726,0.018817,0.015350,True,gvit_stain,mpm
1,-0.002771,-0.019447,0.013087,0.010757,True,gvit_stain,topk
2,-0.207561,-0.240011,-0.174157,-0.179816,True,gvit_stain,span